#!/usr/bin/env python

Import('env')

env_bitcoin = env.Clone()
module_obj = []

env_bitcoin.add_source_files(module_obj, "*.cpp")
env_bitcoin.add_source_files(env_bitcoin.modules_sources, "sha256.c")

module_sources = Glob('modules/bitcoin/*.cpp')

env_bitcoin.add_source_files(env.modules_sources, module_sources)

env_bitcoin.modules_sources += module_obj