#!/usr/bin/env python

Import("env")

env_bitcoin = env.Clone()
module_obj = []

env_bitcoin.add_source_files(module_obj, "*.cpp")
env_bitcoin.add_source_files(module_obj, "*.c")

env_bitcoin.modules_sources += module_obj
